### ISSUE TITLE
Stack installation fails

### ISSUE THREAD

**Issue by rafaqz** [mjakob/hgrib#7]
Installing hgrib with stack I get this error, no matter how many places I install c2hs-0.26.2 in...

At least the following dependencies
    are missing:
    c2hs ==0.26.*

**Comment by mjakob** [comment]
Hello, nice to hear I _almost_ have one confirmed user ;)

I'm afraid I don't know which _stack_ you're reffering to so I won't be able to help you with Haskell installation on/with it. It is correct that hgrib requires c2hs 0.26.\* so the installation should bail out if it doesn't find it.

If you suspect there is something wrong with hgrib's metadata that prevents you to install it, please let me know! Otherwise I will close this issue in a day or two.

Regards, Mattias

**Comment by rafaqz** [comment]
Hah I'm writing a server api and need to parse some grib so this is better
than going via python libs.

Stack is sane dependency management for haskell:
http://docs.haskellstack.org/en/stable/README.html - It mostly solves
dependency hell except in some edge cases like this.

I got it working though, by installing c2hs 0.26.2 with cabal globally and
with stack in the project, after trying with both stack and cabal locally.
Unfortunately 'm not totally sure which one did it in the end. But it does
eventually work if you install it absolutely everywhere.

Hadn't realised that hgrib actually needs the c2hs binary installed not
just the package dependency

On Thu, Feb 11, 2016 at 4:36 PM, Mattias Jakobsson <notifications@github.com

**Comment by mjakob** [comment]
I'm glad to hear you got it working! Hopefully other stack users will have use of this issue. Let me know if you encounter any bugs or miss any features while using hgrib.
